[params]
save_dir="output"
save_in_unique_dir=false
problem=1
x0=true
cCFL=0.5
hx=0.1
ht=0.05
choose_ht=false
Nx=75
theta_kt=1.0
Neta=1.0
ep_coeff=5.26379
choose_cplus_a1=false
frame=1
epL=0.48
epR=0.12
vL=0.0
vR=0.0
Delta=1.0