[params]
save_dir="../output"
save_in_unique_dir=true
problem=0
x0=true
cCFL=0.5
hx=0.05
ht=0.025
choose_ht=false
Nx=75
theta_kt=1.0
Neta=20.0
ep_coeff=10
choose_cplus_a1=false
frame=1
epL=0.4
epR=0.1
vL=0.0
vR=0.0
Delta=5.0